server:
    port: 8082
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/notification
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-group